#!/bin/bash

set -e

pyrus="$PREFIX/bin/pyrus"

# ezComponents' PEAR Channel somehow not works with Pyrus
# so manually download and install the package files.
_ezcomponents_hack() {
    local base_url="http://components.ez.no/get/$package"
    local ezcBase="$base_url/Base-1.8.tgz"
    local ezcConsoleTools="$base_url/ConsoleTools-1.6.1.tgz"

    "$pyrus" install "$ezcBase" "$ezcConsoleTools" > /dev/null
}

# Set up the required channels
"$pyrus" channel-discover "components.ez.no" > /dev/null
"$pyrus" channel-discover "pear.symfony-project.com" > /dev/null
"$pyrus" channel-discover "pear.phpunit.de" > /dev/null

_ezcomponents_hack

"$pyrus" install "phpunit/PHPUnit" > /dev/null

